# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(455, 364)
        self.pushButton_ini = QtGui.QPushButton(Form)
        self.pushButton_ini.setGeometry(QtCore.QRect(360, 60, 85, 27))
        self.pushButton_ini.setObjectName(_fromUtf8("pushButton_ini"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 16, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 16, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 16, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 16, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 16, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 210, 16, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(40, 240, 16, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(100, 30, 61, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(220, 30, 61, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_car11 = QtGui.QLabel(Form)
        self.label_car11.setGeometry(QtCore.QRect(110, 60, 81, 17))
        self.label_car11.setObjectName(_fromUtf8("label_car11"))
        self.label_car21 = QtGui.QLabel(Form)
        self.label_car21.setGeometry(QtCore.QRect(110, 90, 81, 17))
        self.label_car21.setObjectName(_fromUtf8("label_car21"))
        self.label_car31 = QtGui.QLabel(Form)
        self.label_car31.setGeometry(QtCore.QRect(110, 120, 81, 17))
        self.label_car31.setObjectName(_fromUtf8("label_car31"))
        self.label_car41 = QtGui.QLabel(Form)
        self.label_car41.setGeometry(QtCore.QRect(110, 150, 91, 17))
        self.label_car41.setObjectName(_fromUtf8("label_car41"))
        self.label_car51 = QtGui.QLabel(Form)
        self.label_car51.setGeometry(QtCore.QRect(110, 180, 81, 17))
        self.label_car51.setObjectName(_fromUtf8("label_car51"))
        self.label_car61 = QtGui.QLabel(Form)
        self.label_car61.setGeometry(QtCore.QRect(110, 210, 91, 17))
        self.label_car61.setObjectName(_fromUtf8("label_car61"))
        self.label_car71 = QtGui.QLabel(Form)
        self.label_car71.setGeometry(QtCore.QRect(110, 240, 91, 17))
        self.label_car71.setObjectName(_fromUtf8("label_car71"))
        self.label_car32 = QtGui.QLabel(Form)
        self.label_car32.setGeometry(QtCore.QRect(230, 120, 101, 17))
        self.label_car32.setObjectName(_fromUtf8("label_car32"))
        self.label_car22 = QtGui.QLabel(Form)
        self.label_car22.setGeometry(QtCore.QRect(230, 90, 101, 17))
        self.label_car22.setObjectName(_fromUtf8("label_car22"))
        self.label_car12 = QtGui.QLabel(Form)
        self.label_car12.setGeometry(QtCore.QRect(230, 60, 91, 17))
        self.label_car12.setObjectName(_fromUtf8("label_car12"))
        self.label_car62 = QtGui.QLabel(Form)
        self.label_car62.setGeometry(QtCore.QRect(230, 210, 111, 17))
        self.label_car62.setObjectName(_fromUtf8("label_car62"))
        self.label_car42 = QtGui.QLabel(Form)
        self.label_car42.setGeometry(QtCore.QRect(230, 150, 91, 17))
        self.label_car42.setObjectName(_fromUtf8("label_car42"))
        self.label_car52 = QtGui.QLabel(Form)
        self.label_car52.setGeometry(QtCore.QRect(230, 180, 101, 17))
        self.label_car52.setObjectName(_fromUtf8("label_car52"))
        self.label_car72 = QtGui.QLabel(Form)
        self.label_car72.setGeometry(QtCore.QRect(230, 240, 101, 17))
        self.label_car72.setObjectName(_fromUtf8("label_car72"))
        self.label_25 = QtGui.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(380, 140, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_ciclo = QtGui.QLabel(Form)
        self.label_ciclo.setGeometry(QtCore.QRect(380, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_ciclo.setFont(font)
        self.label_ciclo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ciclo.setObjectName(_fromUtf8("label_ciclo"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-10, 260, 481, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 280, 101, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 310, 91, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(10, 340, 121, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_car_pista = QtGui.QLabel(Form)
        self.label_car_pista.setGeometry(QtCore.QRect(100, 280, 41, 20))
        self.label_car_pista.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_pista.setObjectName(_fromUtf8("label_car_pista"))
        self.label_car_box = QtGui.QLabel(Form)
        self.label_car_box.setGeometry(QtCore.QRect(100, 310, 41, 17))
        self.label_car_box.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_box.setObjectName(_fromUtf8("label_car_box"))
        self.label_car_wait = QtGui.QLabel(Form)
        self.label_car_wait.setGeometry(QtCore.QRect(130, 340, 41, 20))
        self.label_car_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_wait.setObjectName(_fromUtf8("label_car_wait"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Controle de Carros", None))
        self.pushButton_ini.setText(_translate("Form", "Iniciar", None))
        self.label.setText(_translate("Form", "Escuderia ", None))
        self.label_2.setText(_translate("Form", "1", None))
        self.label_3.setText(_translate("Form", "2", None))
        self.label_4.setText(_translate("Form", "3", None))
        self.label_5.setText(_translate("Form", "4", None))
        self.label_6.setText(_translate("Form", "5", None))
        self.label_7.setText(_translate("Form", "6", None))
        self.label_8.setText(_translate("Form", "7", None))
        self.label_9.setText(_translate("Form", "Carro 1", None))
        self.label_10.setText(_translate("Form", "Carro 2", None))
        self.label_car11.setText(_translate("Form", "Box", None))
        self.label_car21.setText(_translate("Form", "Box", None))
        self.label_car31.setText(_translate("Form", "Box", None))
        self.label_car41.setText(_translate("Form", "Box", None))
        self.label_car51.setText(_translate("Form", "Box", None))
        self.label_car61.setText(_translate("Form", "Box", None))
        self.label_car71.setText(_translate("Form", "Box", None))
        self.label_car32.setText(_translate("Form", "Box", None))
        self.label_car22.setText(_translate("Form", "Box", None))
        self.label_car12.setText(_translate("Form", "Box", None))
        self.label_car62.setText(_translate("Form", "Box", None))
        self.label_car42.setText(_translate("Form", "Box", None))
        self.label_car52.setText(_translate("Form", "Box", None))
        self.label_car72.setText(_translate("Form", "Box", None))
        self.label_25.setText(_translate("Form", "Ciclo:", None))
        self.label_ciclo.setText(_translate("Form", "0", None))
        self.label_11.setText(_translate("Form", "Carros na Pista:", None))
        self.label_12.setText(_translate("Form", "Carros no Box:", None))
        self.label_13.setText(_translate("Form", "Carros Aguardando: ", None))
        self.label_car_pista.setText(_translate("Form", "0", None))
        self.label_car_box.setText(_translate("Form", "0", None))
        self.label_car_wait.setText(_translate("Form", "0", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

