# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 11:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]', 32), 'invalid')], verbose_name='Login'),
        ),
    ]
